spring:
  profiles:
    active: ${PROFILE:dev}
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  configuration:
    #设置下划线映射为驼峰
    map-underscore-to-camel-case: true
#jwt:
#  auth-path: auth
#  expiration: 604800
#  header: Authorization
#  md5-key: randomKey
#  secret: defaultSecret
#  name-key: name
#  roles-key: roles
#rest:
#  auth-open: false #jwt鉴权机制是否开启(true或者false)
#  sign-open: false #签名机制是否开启(true或false)
server:
  servlet:
    context-path: ${WEBROOT:/}
  port:
    8090