spring:
  datasource:
    url: jdbc:mysql://${DB_IP:140.143.141.105:3306}/${DB_NAME:mysql}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      default-auto-commit: false
